# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_demo',
                'doc_host': 'https://shyamk136.github.io',
                'git_url': 'https://github.com/shyamk136/nbdev_demo',
                'lib_path': 'nbdev_demo'},
  'syms': {'nbdev_demo.core': {'nbdev_demo.core.foo': ('core.html#foo', 'nbdev_demo/core.py')}}}
